package org.trostheide.watercolorprocessor.gui;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.text.DefaultCaret;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class PlotterPanel extends JPanel {

    private final JTextField jsonField;
    private final JCheckBox verboseCheckBox;
    private final JCheckBox debugPositionCheckBox;
    private final SettingsPanel settingsPanel;
    private final JTextArea consoleArea;
    private final VisualizationPanel visPanel;
    private final JButton startButton;
    private final JButton stopButton;
    private final JButton inputButton;
    private final JSpinner stepSpinner;
    private final JLabel settingsSummaryLabel;

    private Process currentProcess;
    private BufferedWriter processInputWriter;

    public PlotterPanel(SettingsPanel settingsPanel) {
        this.settingsPanel = settingsPanel;

        this.settingsPanel.addVisualChangeListener(this::updateVisualSettings);
        this.settingsPanel.addHardwareChangeListener(this::resetManualServer);

        setLayout(new BorderLayout(0, 8));
        setBorder(new EmptyBorder(12, 12, 12, 12));

        // === Top: Configuration ===
        JPanel configPanel = new JPanel(new GridBagLayout());
        configPanel.setBorder(createSection("Driver Configuration"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(4, 8, 4, 8);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // Commands File
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        configPanel.add(label("Commands File"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        jsonField = new JTextField();
        jsonField.setToolTipText("Path to the commands file (generated by Process SVG or Draw SVG)");
        configPanel.add(jsonField, gbc);

        gbc.gridx = 2; gbc.weightx = 0;
        JButton selectJsonBtn = new JButton("Browse");
        selectJsonBtn.addActionListener(e -> selectFile());
        configPanel.add(selectJsonBtn, gbc);

        // Options row
        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0;
        configPanel.add(label("Options"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0; gbc.gridwidth = 2;
        JPanel optionsRow = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        verboseCheckBox = new JCheckBox("Verbose Logging", true);
        debugPositionCheckBox = new JCheckBox("Debug Position", false);
        debugPositionCheckBox.setToolTipText("Query actual hardware position after each move and compare to expected");
        optionsRow.add(verboseCheckBox);
        optionsRow.add(debugPositionCheckBox);
        configPanel.add(optionsRow, gbc);

        // Settings summary strip
        settingsSummaryLabel = new JLabel(" ");
        settingsSummaryLabel.setFont(new Font(Font.MONOSPACED, Font.PLAIN, 11));
        settingsSummaryLabel.setForeground(new Color(160, 170, 180));
        settingsSummaryLabel.setBorder(new EmptyBorder(2, 8, 2, 8));

        JPanel topPanel = new JPanel(new BorderLayout(0, 0));
        topPanel.add(configPanel, BorderLayout.CENTER);
        topPanel.add(settingsSummaryLabel, BorderLayout.SOUTH);
        add(topPanel, BorderLayout.NORTH);

        // === Left: Manual Controls ===
        JPanel manualPanel = new JPanel(new BorderLayout(0, 6));
        manualPanel.setBorder(createSection("Manual Control"));
        manualPanel.setPreferredSize(new Dimension(210, 0));

        JPanel jogPanel = new JPanel(new GridBagLayout());
        GridBagConstraints mc = new GridBagConstraints();
        mc.insets = new Insets(3, 3, 3, 3);
        mc.fill = GridBagConstraints.BOTH;

        mc.gridx = 0; mc.gridy = 0; mc.gridwidth = 3;
        JPanel stepPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 4, 0));
        stepPanel.setOpaque(false);
        stepPanel.add(label("Step (mm)"));
        stepSpinner = new JSpinner(new SpinnerNumberModel(10.0, 0.1, 100.0, 1.0));
        stepPanel.add(stepSpinner);
        jogPanel.add(stepPanel, mc);

        JButton btnUp = createJogButton("Up");
        JButton btnDown = createJogButton("Down");
        JButton btnLeft = createJogButton("Left");
        JButton btnRight = createJogButton("Right");

        java.awt.event.ActionListener moveAction = e -> {
            double step = (Double) stepSpinner.getValue();
            double dx = 0, dy = 0;
            boolean flipY = settingsPanel.isFlipY();
            boolean upSign = settingsPanel.isOriginBottom() ^ flipY;
            if (e.getSource() == btnUp) dy = upSign ? step : -step;
            else if (e.getSource() == btnDown) dy = upSign ? -step : step;
            else if (e.getSource() == btnLeft) dx = settingsPanel.isOriginRight() ? step : -step;
            else if (e.getSource() == btnRight) dx = settingsPanel.isOriginRight() ? -step : step;
            runManualMove(dx, dy);
        };
        btnUp.addActionListener(moveAction);
        btnDown.addActionListener(moveAction);
        btnLeft.addActionListener(moveAction);
        btnRight.addActionListener(moveAction);

        mc.gridwidth = 1;
        mc.gridx = 1; mc.gridy = 1; jogPanel.add(btnUp, mc);
        mc.gridx = 0; mc.gridy = 2; jogPanel.add(btnLeft, mc);
        mc.gridx = 2; mc.gridy = 2; jogPanel.add(btnRight, mc);
        mc.gridx = 1; mc.gridy = 3; jogPanel.add(btnDown, mc);

        manualPanel.add(jogPanel, BorderLayout.CENTER);

        JPanel manualSouth = new JPanel();
        manualSouth.setLayout(new BoxLayout(manualSouth, BoxLayout.Y_AXIS));

        JPanel penPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 8, 4));
        JButton penUpBtn = new JButton("Pen UP");
        penUpBtn.putClientProperty("JButton.buttonType", "roundRect");
        penUpBtn.addActionListener(e -> runManualPen("UP"));
        JButton penDownBtn = new JButton("Pen DOWN");
        penDownBtn.putClientProperty("JButton.buttonType", "roundRect");
        penDownBtn.addActionListener(e -> runManualPen("DOWN"));
        penPanel.add(penUpBtn);
        penPanel.add(penDownBtn);
        manualSouth.add(penPanel);

        JPanel gcodeInputPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 4, 4));
        gcodeInputPanel.add(label("G-code"));
        JTextField gcodeField = new JTextField(10);
        gcodeField.setToolTipText("Send raw G-code (e.g. $$ for settings, G0 Z5 to test Z axis)");
        gcodeInputPanel.add(gcodeField);
        JButton gcodeSendBtn = new JButton("Send");
        gcodeSendBtn.putClientProperty("JButton.buttonType", "roundRect");
        Runnable sendGcode = () -> {
            String cmd = gcodeField.getText().trim();
            if (!cmd.isEmpty()) {
                ensureManualServer();
                sendServerCommand("RAW " + cmd);
            }
        };
        gcodeSendBtn.addActionListener(e -> sendGcode.run());
        gcodeField.addActionListener(e -> sendGcode.run());
        gcodeInputPanel.add(gcodeSendBtn);
        manualSouth.add(gcodeInputPanel);

        manualPanel.add(manualSouth, BorderLayout.SOUTH);

        // Key bindings for arrow jog
        InputMap im = manualPanel.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ActionMap am = manualPanel.getActionMap();
        im.put(KeyStroke.getKeyStroke("UP"), "jogUp");
        im.put(KeyStroke.getKeyStroke("DOWN"), "jogDown");
        im.put(KeyStroke.getKeyStroke("LEFT"), "jogLeft");
        im.put(KeyStroke.getKeyStroke("RIGHT"), "jogRight");
        am.put("jogUp", new AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double s = (Double) stepSpinner.getValue();
                boolean up = settingsPanel.isOriginBottom() ^ settingsPanel.isFlipY();
                runManualMove(0, up ? s : -s);
            }
        });
        am.put("jogDown", new AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double s = (Double) stepSpinner.getValue();
                boolean up = settingsPanel.isOriginBottom() ^ settingsPanel.isFlipY();
                runManualMove(0, up ? -s : s);
            }
        });
        am.put("jogLeft", new AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double s = (Double) stepSpinner.getValue();
                runManualMove(settingsPanel.isOriginRight() ? s : -s, 0);
            }
        });
        am.put("jogRight", new AbstractAction() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double s = (Double) stepSpinner.getValue();
                runManualMove(settingsPanel.isOriginRight() ? -s : s, 0);
            }
        });

        add(manualPanel, BorderLayout.WEST);

        // === Center: Split Pane for Console and Visualization ===
        consoleArea = new JTextArea();
        consoleArea.setEditable(false);
        consoleArea.setFont(new Font("JetBrains Mono", Font.PLAIN, 12));
        consoleArea.setBackground(new Color(30, 30, 30));
        consoleArea.setForeground(new Color(180, 220, 180));
        consoleArea.setCaretColor(new Color(180, 220, 180));
        DefaultCaret caret = (DefaultCaret) consoleArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        JScrollPane consoleScroll = new JScrollPane(consoleArea);
        consoleScroll.setBorder(createSection("Driver Output"));

        visPanel = new VisualizationPanel();

        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, consoleScroll, visPanel);
        splitPane.setResizeWeight(0.35);
        splitPane.setDividerLocation(340);

        add(splitPane, BorderLayout.CENTER);

        // === Bottom: Control Buttons ===
        JPanel controlPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 12, 6));

        startButton = new JButton("Start Plot");
        startButton.setFont(startButton.getFont().deriveFont(Font.BOLD));
        startButton.setPreferredSize(new Dimension(130, 36));
        startButton.putClientProperty("JButton.buttonType", "roundRect");
        startButton.setBackground(new Color(56, 118, 29));
        startButton.setForeground(Color.WHITE);
        startButton.addActionListener(e -> startProcess());

        inputButton = new JButton("Confirm / Enter");
        inputButton.setPreferredSize(new Dimension(140, 36));
        inputButton.putClientProperty("JButton.buttonType", "roundRect");
        inputButton.setEnabled(false);
        inputButton.addActionListener(e -> sendInput("\n"));

        stopButton = new JButton("Stop");
        stopButton.setPreferredSize(new Dimension(100, 36));
        stopButton.putClientProperty("JButton.buttonType", "roundRect");
        stopButton.setBackground(new Color(183, 28, 28));
        stopButton.setForeground(Color.WHITE);
        stopButton.setEnabled(false);
        stopButton.addActionListener(e -> stopProcess());

        JButton resetViewBtn = new JButton("Reset Position");
        resetViewBtn.setPreferredSize(new Dimension(130, 36));
        resetViewBtn.putClientProperty("JButton.buttonType", "roundRect");
        resetViewBtn.addActionListener(e -> visPanel.resetOverlay());

        controlPanel.add(startButton);
        controlPanel.add(inputButton);
        controlPanel.add(stopButton);
        controlPanel.add(resetViewBtn);

        add(controlPanel, BorderLayout.SOUTH);

        // Force initial visual update to match settings
        SwingUtilities.invokeLater(this::updateVisualSettings);
    }

    private JButton createJogButton(String text) {
        JButton btn = new JButton(text);
        btn.setPreferredSize(new Dimension(60, 32));
        btn.putClientProperty("JButton.buttonType", "roundRect");
        btn.setFont(btn.getFont().deriveFont(11f));
        return btn;
    }

    private JLabel label(String text) {
        JLabel l = new JLabel(text);
        l.setFont(l.getFont().deriveFont(12f));
        return l;
    }

    private TitledBorder createSection(String title) {
        TitledBorder border = BorderFactory.createTitledBorder(title);
        border.setTitleFont(border.getTitleFont().deriveFont(Font.BOLD, 12f));
        return border;
    }

    private void selectFile() {
        JFileChooser fc = new JFileChooser();
        File current = new File(jsonField.getText());
        if (current.exists())
            fc.setSelectedFile(current);
        else
            fc.setCurrentDirectory(new File("."));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jsonField.setText(fc.getSelectedFile().getAbsolutePath());
            visPanel.loadFromJson(fc.getSelectedFile());
        }
    }

    private void startProcess() {
        String jsonPath = jsonField.getText().trim();
        if (jsonPath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a JSON file.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        File jsonFile = new File(jsonPath);
        if (!jsonFile.exists()) {
            JOptionPane.showMessageDialog(this, "File not found: " + jsonPath, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Auto-save config so driver sees latest changes
        settingsPanel.saveConfigSilent();

        // Apply visual overlay transform to JSON if user has dragged/resized
        if (visPanel.hasOverlayTransform()) {
            try {
                jsonFile = applyOverlayToJson(jsonFile,
                        visPanel.getOverlayScale(), visPanel.getOverlayOffsetX(), visPanel.getOverlayOffsetY());
                jsonField.setText(jsonFile.getAbsolutePath());
                appendToConsole("Applied visual transform: scale=" +
                        String.format("%.2f", visPanel.getOverlayScale()) +
                        " offset=(" + String.format("%.1f, %.1f", visPanel.getOverlayOffsetX(), visPanel.getOverlayOffsetY()) + ")");
                visPanel.resetOverlay();
            } catch (Exception ex) {
                appendToConsole("Warning: could not apply visual transform: " + ex.getMessage());
            }
        }

        // Reload vis with the (possibly baked) JSON
        visPanel.loadFromJson(jsonFile);
        updateVisualSettings();

        List<String> cmd = buildDriverCommand();
        cmd.add(2, jsonFile.getAbsolutePath()); // insert after driver.py path

        if (debugPositionCheckBox.isSelected()) {
            cmd.add("--debug-position");
        }

        boolean isPortrait = settingsPanel.isPortrait();
        boolean needsAxisSwap = isPortrait && settingsPanel.getMachineWidth() > settingsPanel.getMachineHeight();
        String alignment = settingsPanel.getCanvasAlignment();
        if (alignment != null && !alignment.isEmpty()) {
            if (needsAxisSwap) {
                alignment = translateAlignmentForPortrait(alignment,
                        settingsPanel.isOriginRight(), settingsPanel.isOriginBottom());
            }
            cmd.add("--canvas-align");
            cmd.add(alignment.toLowerCase().replace(" ", "-"));
        }

        cmd.add("--padding-x");
        cmd.add(String.valueOf(settingsPanel.getPaddingX()));
        cmd.add("--padding-y");
        cmd.add(String.valueOf(settingsPanel.getPaddingY()));

        int rotation = settingsPanel.getViewRotation();
        if (rotation != 0) {
            cmd.add("--data-rotation");
            cmd.add(String.valueOf(rotation));
        }

        cmd.add("--report-position");

        consoleArea.setText("");
        appendToConsole("Starting driver...");
        appendToConsole("Command: " + String.join(" ", cmd));

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.redirectErrorStream(true);

        try {
            currentProcess = pb.start();
            processInputWriter = new BufferedWriter(new OutputStreamWriter(currentProcess.getOutputStream()));

            startButton.setEnabled(false);
            stopButton.setEnabled(true);
            inputButton.setEnabled(true);

            settingsPanel.setSettingsEnabled(false);

            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(currentProcess.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        final String l = line;

                        if (l.startsWith("POS:")) {
                            try {
                                String[] parts = l.split(":");
                                double x = Double.parseDouble(parts[2]);
                                double y = Double.parseDouble(parts[4]);
                                SwingUtilities.invokeLater(() -> visPanel.updatePosition(x, y));
                            } catch (Exception parseEx) {
                                // ignore parse errors
                            }
                            continue;
                        }

                        if (l.contains("INFO: Connection Successful")) {
                            updateStatus(true);
                        } else if (l.contains("ERROR: Could not connect") || l.contains("Connection Failed")) {
                            updateStatus(false);
                        }

                        SwingUtilities.invokeLater(() -> appendToConsole(l));
                    }
                } catch (IOException e) {
                    if (currentProcess != null && currentProcess.isAlive()) {
                        e.printStackTrace();
                    }
                } finally {
                    SwingUtilities.invokeLater(() -> {
                        appendToConsole("--- Process Exited ---");
                        updateStatus(false);
                        processCleanup();
                    });
                }
            }).start();

        } catch (IOException e) {
            appendToConsole("Error starting process: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void stopProcess() {
        if (currentProcess != null && currentProcess.isAlive()) {
            currentProcess.destroy();
            appendToConsole("--- Process Killed by User ---");
        }
        processCleanup();
    }

    private void sendInput(String input) {
        if (currentProcess != null && currentProcess.isAlive() && processInputWriter != null) {
            try {
                processInputWriter.write(input);
                processInputWriter.flush();
            } catch (IOException e) {
                appendToConsole("Error sending input: " + e.getMessage());
            }
        }
    }

    private void processCleanup() {
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
        inputButton.setEnabled(false);

        settingsPanel.setSettingsEnabled(true);

        currentProcess = null;
        processInputWriter = null;
    }

    private Process manualServerProcess;
    private BufferedWriter manualServerWriter;

    private List<String> buildDriverCommand() {
        List<String> cmd = new ArrayList<>();
        cmd.add(settingsPanel.getPythonPath());
        cmd.add("driver/driver.py");

        boolean isGcode = "gcode".equals(settingsPanel.getBackend());
        if (isGcode) {
            cmd.add("--backend");
            cmd.add("gcode");
            cmd.add("--serial-port");
            cmd.add(settingsPanel.getSerialPort());
            cmd.add("--machine-width");
            cmd.add(String.valueOf(settingsPanel.getMachineWidth()));
            cmd.add("--machine-height");
            cmd.add(String.valueOf(settingsPanel.getMachineHeight()));
        }

        if (settingsPanel.isMockMode())
            cmd.add("--mock");

        cmd.add("--machine-origin");
        cmd.add(settingsPanel.getMachineOrigin().toLowerCase().replace(" ", "-"));

        boolean isPortrait = settingsPanel.isPortrait();
        boolean needsAxisSwap = isPortrait && settingsPanel.getMachineWidth() > settingsPanel.getMachineHeight();
        if (needsAxisSwap)
            cmd.add("--portrait");
        if (settingsPanel.isFlipY())
            cmd.add("--flip-y");
        if (settingsPanel.isSwapXY())
            cmd.add("--swap-xy");
        if (verboseCheckBox.isSelected())
            cmd.add("--verbose");

        if (!isGcode) {
            cmd.add("--model");
            cmd.add(String.valueOf(settingsPanel.getPlotterModelIndex() + 1));
            cmd.add("--speed-down");
            cmd.add(String.valueOf(settingsPanel.getDrawSpeed()));
            cmd.add("--speed-up");
            cmd.add(String.valueOf(settingsPanel.getTravelSpeed()));
            cmd.add("--pen-up");
            cmd.add(String.valueOf(settingsPanel.getPenUpHeight()));
            cmd.add("--pen-down");
            cmd.add(String.valueOf(settingsPanel.getPenDownHeight()));
        }

        cmd.add("--config");
        cmd.add(settingsPanel.getCurrentConfigFile().getAbsolutePath());

        return cmd;
    }

    private void ensureManualServer() {
        if (manualServerProcess != null && manualServerProcess.isAlive()) {
            return;
        }

        settingsPanel.saveConfigSilent();

        try {
            List<String> cmd = buildDriverCommand();
            cmd.add("--interactive-server");

            appendToConsole("Starting Manual Control Server...");
            ProcessBuilder pb = new ProcessBuilder(cmd);
            pb.redirectErrorStream(true);
            manualServerProcess = pb.start();
            manualServerWriter = new BufferedWriter(new OutputStreamWriter(manualServerProcess.getOutputStream()));

            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(manualServerProcess.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        final String l = line;

                        if (l.contains("INFO: Connection Successful")) {
                            updateStatus(true);
                        } else if (l.contains("ERROR: Could not connect")) {
                            updateStatus(false);
                        }

                        SwingUtilities.invokeLater(() -> appendToConsole("[SRV] " + l));
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();

        } catch (IOException e) {
            e.printStackTrace();
            appendToConsole("Failed to start server: " + e.getMessage());
        }
    }

    private void sendServerCommand(String cmd) {
        if (manualServerProcess != null && manualServerProcess.isAlive()) {
            try {
                manualServerWriter.write(cmd + "\n");
                manualServerWriter.flush();
            } catch (IOException e) {
                appendToConsole("Error sending to server: " + e.getMessage());
            }
        }
    }

    private void resetManualServer() {
        if (manualServerProcess != null && manualServerProcess.isAlive()) {
            manualServerProcess.destroy();
            manualServerProcess = null;
            appendToConsole("[SRV] Server reset due to configuration change.");
        }
    }

    private void runManualMove(double dx, double dy) {
        ensureManualServer();
        sendServerCommand(String.format(java.util.Locale.US, "MOVE %f %f", dx, dy));
    }

    private void runManualPen(String direction) {
        ensureManualServer();
        sendServerCommand("PEN " + direction);
    }

    private static String translateAlignmentForPortrait(String label, boolean originRight, boolean originBottom) {
        boolean xor = originRight ^ originBottom;
        if (xor) {
            if ("Top Left".equals(label)) return "Bottom Right";
            if ("Bottom Right".equals(label)) return "Top Left";
        } else {
            if ("Top Right".equals(label)) return "Bottom Left";
            if ("Bottom Left".equals(label)) return "Top Right";
        }
        return label;
    }

    public void loadJsonFile(File file) {
        jsonField.setText(file.getAbsolutePath());
        visPanel.loadFromJson(file);
        updateVisualSettings();
    }

    private void updateSettingsSummary() {
        String backend = "gcode".equals(settingsPanel.getBackend()) ? "GRBL" : "AxiDraw";
        String port = "gcode".equals(settingsPanel.getBackend())
                ? " | " + settingsPanel.getSerialPort() : "";
        settingsSummaryLabel.setText(String.format(
                "%s%s | %s | %.0f x %.0f mm | Align: %s | %s",
                backend, port,
                settingsPanel.getMachineOrigin(),
                settingsPanel.getMachineWidth(), settingsPanel.getMachineHeight(),
                settingsPanel.getCanvasAlignment(),
                settingsPanel.getOrientation()));
    }

    private void updateVisualSettings() {
        updateSettingsSummary();
        visPanel.setMachineSize(settingsPanel.getMachineWidth(), settingsPanel.getMachineHeight());
        visPanel.setMachineOrigin(settingsPanel.getMachineOrigin());

        visPanel.setDataInvertX(settingsPanel.isInvertX());
        visPanel.setDataInvertY(settingsPanel.isInvertY());
        visPanel.setFlipY(settingsPanel.isFlipY());

        visPanel.setSwapXY(settingsPanel.isSwapXY());
        visPanel.setCanvasAlignment(settingsPanel.getCanvasAlignment());
        visPanel.setOrientation(settingsPanel.getOrientation());
        visPanel.setViewRotation(settingsPanel.getViewRotation());
        visPanel.setPadding(settingsPanel.getPaddingX(), settingsPanel.getPaddingY());

        List<VisualizationPanel.Station> visualStations = new ArrayList<>();
        Map<String, StationConfig> stations = settingsPanel.getStations();
        if (stations != null) {
            for (Map.Entry<String, StationConfig> entry : stations.entrySet()) {
                StationConfig cfg = entry.getValue();
                visualStations.add(new VisualizationPanel.Station(entry.getKey(), cfg.x(), cfg.y()));
            }
        }
        visPanel.setStations(visualStations);
    }

    private void appendToConsole(String text) {
        consoleArea.append(text + "\n");
    }

    private void updateStatus(boolean connected) {
        Window win = SwingUtilities.getWindowAncestor(this);
        if (win instanceof MainFrame) {
            ((MainFrame) win).setConnectionStatus(connected);
        }
    }

    private File applyOverlayToJson(File original, double scale, double offsetX, double offsetY) throws Exception {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(original);

        // Find content bounds for scale-around-center
        double minX = Double.MAX_VALUE, maxX = -Double.MAX_VALUE;
        double minY = Double.MAX_VALUE, maxY = -Double.MAX_VALUE;

        for (JsonNode layer : root.get("layers")) {
            for (JsonNode cmd : layer.get("commands")) {
                if ("DRAW".equals(cmd.get("op").asText())) {
                    for (JsonNode p : cmd.get("points")) {
                        double x = p.get("x").asDouble();
                        double y = p.get("y").asDouble();
                        minX = Math.min(minX, x); maxX = Math.max(maxX, x);
                        minY = Math.min(minY, y); maxY = Math.max(maxY, y);
                    }
                } else if ("MOVE".equals(cmd.get("op").asText())) {
                    double x = cmd.get("x").asDouble();
                    double y = cmd.get("y").asDouble();
                    minX = Math.min(minX, x); maxX = Math.max(maxX, x);
                    minY = Math.min(minY, y); maxY = Math.max(maxY, y);
                }
            }
        }

        double cx = (minX + maxX) / 2.0;
        double cy = (minY + maxY) / 2.0;

        // Transform all coordinates
        for (JsonNode layer : root.get("layers")) {
            for (JsonNode cmd : layer.get("commands")) {
                if ("DRAW".equals(cmd.get("op").asText())) {
                    for (JsonNode p : cmd.get("points")) {
                        double x = (p.get("x").asDouble() - cx) * scale + cx + offsetX;
                        double y = (p.get("y").asDouble() - cy) * scale + cy + offsetY;
                        ((ObjectNode) p).put("x", x);
                        ((ObjectNode) p).put("y", y);
                    }
                } else if ("MOVE".equals(cmd.get("op").asText())) {
                    double x = (cmd.get("x").asDouble() - cx) * scale + cx + offsetX;
                    double y = (cmd.get("y").asDouble() - cy) * scale + cy + offsetY;
                    ((ObjectNode) cmd).put("x", x);
                    ((ObjectNode) cmd).put("y", y);
                }
            }
        }

        // Update bounds in metadata
        if (root.has("metadata") && ((ObjectNode) root.get("metadata")).has("bounds")) {
            ObjectNode bounds = (ObjectNode) root.get("metadata").get("bounds");
            bounds.put("minX", (bounds.get("minX").asDouble() - cx) * scale + cx + offsetX);
            bounds.put("maxX", (bounds.get("maxX").asDouble() - cx) * scale + cx + offsetX);
            bounds.put("minY", (bounds.get("minY").asDouble() - cy) * scale + cy + offsetY);
            bounds.put("maxY", (bounds.get("maxY").asDouble() - cy) * scale + cy + offsetY);
        }

        File transformed = File.createTempFile("transformed_", ".json");
        transformed.deleteOnExit();
        mapper.writerWithDefaultPrettyPrinter().writeValue(transformed, root);
        return transformed;
    }
}
