package org.trostheide.watercolorprocessor.gui;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;
import javax.swing.text.DefaultCaret;
import java.awt.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class PlotterPanel extends JPanel {

    private final JTextField jsonField;
    private final JTextField pythonPathField;
    private final JCheckBox verboseCheckBox;
    private final JCheckBox debugPositionCheckBox;
    private final SettingsPanel settingsPanel;
    private final JTextArea consoleArea;
    private final VisualizationPanel visPanel;
    private final JButton startButton;
    private final JButton stopButton;
    private final JButton inputButton;

    private Process currentProcess;
    private BufferedWriter processInputWriter;

    public PlotterPanel(SettingsPanel settingsPanel) {
        this.settingsPanel = settingsPanel;

        // Define how to run driver commands from settings panel
        this.settingsPanel.setManualSession(new SettingsPanel.ManualControlSession() {
            @Override
            public void sendRelativeMove(double dx, double dy) {
                ensureManualServer();
                sendServerCommand(String.format(java.util.Locale.US, "MOVE %f %f", dx, dy));
            }

            @Override
            public void sendPenCommand(String direction, int height) {
                ensureManualServer();
                sendServerCommand("PEN " + direction);
            }

            @Override
            public void resetServer() {
                if (manualServerProcess != null && manualServerProcess.isAlive()) {
                    manualServerProcess.destroy();
                    manualServerProcess = null;
                    appendToConsole("[SRV] Server reset due to configuration change.");
                }
            }
        });

        this.settingsPanel.addVisualChangeListener(this::updateVisualSettings);

        setLayout(new BorderLayout(0, 8));
        setBorder(new EmptyBorder(12, 12, 12, 12));

        // === Top: Configuration ===
        JPanel configPanel = new JPanel(new GridBagLayout());
        configPanel.setBorder(createSection("Driver Configuration"));
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(4, 8, 4, 8);
        gbc.fill = GridBagConstraints.HORIZONTAL;

        // JSON File
        gbc.gridx = 0; gbc.gridy = 0; gbc.weightx = 0;
        configPanel.add(label("JSON File"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        jsonField = new JTextField();
        jsonField.setToolTipText("Path to the commands.json file generated by the processor");
        configPanel.add(jsonField, gbc);

        gbc.gridx = 2; gbc.weightx = 0;
        JButton selectJsonBtn = new JButton("Browse");
        selectJsonBtn.addActionListener(e -> selectFile());
        configPanel.add(selectJsonBtn, gbc);

        // Python Path
        gbc.gridx = 0; gbc.gridy = 1; gbc.weightx = 0;
        configPanel.add(label("Python Path"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0;
        String defaultPython = System.getProperty("os.name").toLowerCase().contains("win") ? "python" : "python3";
        pythonPathField = new JTextField(defaultPython);
        pythonPathField.setToolTipText("Path to the Python interpreter (python or python3)");
        configPanel.add(pythonPathField, gbc);

        // Options row
        gbc.gridx = 0; gbc.gridy = 2; gbc.weightx = 0;
        configPanel.add(label("Options"), gbc);

        gbc.gridx = 1; gbc.weightx = 1.0; gbc.gridwidth = 2;
        JPanel optionsRow = new JPanel(new FlowLayout(FlowLayout.LEFT, 8, 0));
        verboseCheckBox = new JCheckBox("Verbose Logging", true);
        debugPositionCheckBox = new JCheckBox("Debug Position", false);
        debugPositionCheckBox.setToolTipText("Query actual hardware position after each move and compare to expected");
        optionsRow.add(verboseCheckBox);
        optionsRow.add(debugPositionCheckBox);
        configPanel.add(optionsRow, gbc);

        add(configPanel, BorderLayout.NORTH);

        // === Center: Split Pane for Console and Visualization ===
        consoleArea = new JTextArea();
        consoleArea.setEditable(false);
        consoleArea.setFont(new Font("JetBrains Mono", Font.PLAIN, 12));
        consoleArea.setBackground(new Color(30, 30, 30));
        consoleArea.setForeground(new Color(180, 220, 180));
        consoleArea.setCaretColor(new Color(180, 220, 180));
        DefaultCaret caret = (DefaultCaret) consoleArea.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);

        JScrollPane consoleScroll = new JScrollPane(consoleArea);
        consoleScroll.setBorder(createSection("Driver Output"));

        visPanel = new VisualizationPanel();

        JSplitPane splitPane = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, consoleScroll, visPanel);
        splitPane.setResizeWeight(0.35);
        splitPane.setDividerLocation(380);

        add(splitPane, BorderLayout.CENTER);

        // === Bottom: Control Buttons ===
        JPanel controlPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 12, 6));

        startButton = new JButton("Start Plot");
        startButton.setFont(startButton.getFont().deriveFont(Font.BOLD));
        startButton.setPreferredSize(new Dimension(130, 36));
        startButton.putClientProperty("JButton.buttonType", "roundRect");
        startButton.setBackground(new Color(56, 118, 29));
        startButton.setForeground(Color.WHITE);
        startButton.addActionListener(e -> startProcess());

        inputButton = new JButton("Confirm / Enter");
        inputButton.setPreferredSize(new Dimension(140, 36));
        inputButton.putClientProperty("JButton.buttonType", "roundRect");
        inputButton.setEnabled(false);
        inputButton.addActionListener(e -> sendInput("\n"));

        stopButton = new JButton("Stop");
        stopButton.setPreferredSize(new Dimension(100, 36));
        stopButton.putClientProperty("JButton.buttonType", "roundRect");
        stopButton.setBackground(new Color(183, 28, 28));
        stopButton.setForeground(Color.WHITE);
        stopButton.setEnabled(false);
        stopButton.addActionListener(e -> stopProcess());

        controlPanel.add(startButton);
        controlPanel.add(inputButton);
        controlPanel.add(stopButton);

        add(controlPanel, BorderLayout.SOUTH);

        // Force initial visual update to match settings
        SwingUtilities.invokeLater(this::updateVisualSettings);
    }

    private JLabel label(String text) {
        JLabel l = new JLabel(text);
        l.setFont(l.getFont().deriveFont(12f));
        return l;
    }

    private TitledBorder createSection(String title) {
        TitledBorder border = BorderFactory.createTitledBorder(title);
        border.setTitleFont(border.getTitleFont().deriveFont(Font.BOLD, 12f));
        return border;
    }

    private void selectFile() {
        JFileChooser fc = new JFileChooser();
        File current = new File(jsonField.getText());
        if (current.exists())
            fc.setSelectedFile(current);
        else
            fc.setCurrentDirectory(new File("."));

        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jsonField.setText(fc.getSelectedFile().getAbsolutePath());
            visPanel.loadFromJson(fc.getSelectedFile());
        }
    }

    private void startProcess() {
        String jsonPath = jsonField.getText().trim();
        if (jsonPath.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a JSON file.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        File jsonFile = new File(jsonPath);
        if (!jsonFile.exists()) {
            JOptionPane.showMessageDialog(this, "File not found: " + jsonPath, "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Auto-save config so driver sees latest changes
        settingsPanel.saveConfigSilent();

        // Reload vis just in case
        visPanel.loadFromJson(jsonFile);
        updateVisualSettings();

        List<String> cmd = new ArrayList<>();
        cmd.add(pythonPathField.getText().trim());
        cmd.add("driver/driver.py");
        cmd.add(jsonFile.getAbsolutePath());

        boolean isGcode = "gcode".equals(settingsPanel.getBackend());

        if (isGcode) {
            cmd.add("--backend");
            cmd.add("gcode");
            cmd.add("--serial-port");
            cmd.add(settingsPanel.getSerialPort());
            cmd.add("--machine-width");
            cmd.add(String.valueOf(settingsPanel.getMachineWidth()));
            cmd.add("--machine-height");
            cmd.add(String.valueOf(settingsPanel.getMachineHeight()));
        }

        if (settingsPanel.isMockMode()) {
            cmd.add("--mock");
        }

        cmd.add("--machine-origin");
        cmd.add(settingsPanel.getMachineOrigin().toLowerCase().replace(" ", "-"));

        boolean isPortrait = settingsPanel.isPortrait();
        boolean needsAxisSwap = isPortrait && settingsPanel.getMachineWidth() > settingsPanel.getMachineHeight();
        if (needsAxisSwap) {
            cmd.add("--portrait");
        }
        if (settingsPanel.isFlipY()) {
            cmd.add("--flip-y");
        }
        if (settingsPanel.isSwapXY()) {
            cmd.add("--swap-xy");
        }
        if (verboseCheckBox.isSelected()) {
            cmd.add("--verbose");
        }
        if (debugPositionCheckBox.isSelected()) {
            cmd.add("--debug-position");
        }

        if (!isGcode) {
            cmd.add("--model");
            cmd.add(String.valueOf(settingsPanel.getPlotterModelIndex() + 1));

            cmd.add("--speed-down");
            cmd.add(String.valueOf(settingsPanel.getDrawSpeed()));
            cmd.add("--speed-up");
            cmd.add(String.valueOf(settingsPanel.getTravelSpeed()));

            cmd.add("--pen-up");
            cmd.add(String.valueOf(settingsPanel.getPenUpHeight()));
            cmd.add("--pen-down");
            cmd.add(String.valueOf(settingsPanel.getPenDownHeight()));
        }

        String alignment = settingsPanel.getCanvasAlignment();
        if (alignment != null && !alignment.isEmpty()) {
            if (needsAxisSwap) {
                alignment = translateAlignmentForPortrait(alignment,
                        settingsPanel.isOriginRight(), settingsPanel.isOriginBottom());
            }
            cmd.add("--canvas-align");
            cmd.add(alignment.toLowerCase().replace(" ", "-"));
        }

        cmd.add("--padding-x");
        cmd.add(String.valueOf(settingsPanel.getPaddingX()));
        cmd.add("--padding-y");
        cmd.add(String.valueOf(settingsPanel.getPaddingY()));

        int rotation = settingsPanel.getViewRotation();
        if (rotation != 0) {
            cmd.add("--data-rotation");
            cmd.add(String.valueOf(rotation));
        }

        cmd.add("--report-position");
        cmd.add("--config");
        cmd.add(settingsPanel.getCurrentConfigFile().getAbsolutePath());

        consoleArea.setText("");
        appendToConsole("Starting driver...");
        appendToConsole("Command: " + String.join(" ", cmd));

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.redirectErrorStream(true);

        try {
            currentProcess = pb.start();
            processInputWriter = new BufferedWriter(new OutputStreamWriter(currentProcess.getOutputStream()));

            startButton.setEnabled(false);
            stopButton.setEnabled(true);
            inputButton.setEnabled(true);

            settingsPanel.setSettingsEnabled(false);
            pythonPathField.setEnabled(false);

            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(currentProcess.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        final String l = line;

                        if (l.startsWith("POS:")) {
                            try {
                                String[] parts = l.split(":");
                                double x = Double.parseDouble(parts[2]);
                                double y = Double.parseDouble(parts[4]);
                                SwingUtilities.invokeLater(() -> visPanel.updatePosition(x, y));
                            } catch (Exception parseEx) {
                                // ignore parse errors
                            }
                            continue;
                        }

                        if (l.contains("INFO: Connection Successful")) {
                            updateStatus(true);
                        } else if (l.contains("ERROR: Could not connect") || l.contains("Connection Failed")) {
                            updateStatus(false);
                        }

                        SwingUtilities.invokeLater(() -> appendToConsole(l));
                    }
                } catch (IOException e) {
                    if (currentProcess != null && currentProcess.isAlive()) {
                        e.printStackTrace();
                    }
                } finally {
                    SwingUtilities.invokeLater(() -> {
                        appendToConsole("--- Process Exited ---");
                        updateStatus(false);
                        processCleanup();
                    });
                }
            }).start();

        } catch (IOException e) {
            appendToConsole("Error starting process: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void stopProcess() {
        if (currentProcess != null && currentProcess.isAlive()) {
            currentProcess.destroy();
            appendToConsole("--- Process Killed by User ---");
        }
        processCleanup();
    }

    private void sendInput(String input) {
        if (currentProcess != null && currentProcess.isAlive() && processInputWriter != null) {
            try {
                processInputWriter.write(input);
                processInputWriter.flush();
            } catch (IOException e) {
                appendToConsole("Error sending input: " + e.getMessage());
            }
        }
    }

    private void processCleanup() {
        startButton.setEnabled(true);
        stopButton.setEnabled(false);
        inputButton.setEnabled(false);

        settingsPanel.setSettingsEnabled(true);
        pythonPathField.setEnabled(true);

        currentProcess = null;
        processInputWriter = null;
    }

    private Process manualServerProcess;
    private BufferedWriter manualServerWriter;

    private void ensureManualServer() {
        if (manualServerProcess != null && manualServerProcess.isAlive()) {
            return;
        }

        try {
            List<String> cmd = new ArrayList<>();
            cmd.add(pythonPathField.getText());
            cmd.add("driver/driver.py");
            cmd.add("--interactive-server");

            if ("gcode".equals(settingsPanel.getBackend())) {
                cmd.add("--backend");
                cmd.add("gcode");
            }

            if (settingsPanel.isMockMode())
                cmd.add("--mock");
            if (verboseCheckBox.isSelected())
                cmd.add("--verbose");
            cmd.add("--machine-origin");
            cmd.add(settingsPanel.getMachineOrigin().toLowerCase().replace(" ", "-"));
            if (settingsPanel.isSwapXY())
                cmd.add("--swap-xy");

            cmd.add("--config");
            cmd.add(settingsPanel.getCurrentConfigFile().getAbsolutePath());

            appendToConsole("Starting Manual Control Server...");
            ProcessBuilder pb = new ProcessBuilder(cmd);
            pb.redirectErrorStream(true);
            manualServerProcess = pb.start();
            manualServerWriter = new BufferedWriter(new OutputStreamWriter(manualServerProcess.getOutputStream()));

            new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(
                        new InputStreamReader(manualServerProcess.getInputStream()))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        final String l = line;

                        if (l.contains("INFO: Connection Successful")) {
                            updateStatus(true);
                        } else if (l.contains("ERROR: Could not connect")) {
                            updateStatus(false);
                        }

                        SwingUtilities.invokeLater(() -> appendToConsole("[SRV] " + l));
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }).start();

        } catch (IOException e) {
            e.printStackTrace();
            appendToConsole("Failed to start server: " + e.getMessage());
        }
    }

    private void sendServerCommand(String cmd) {
        if (manualServerProcess != null && manualServerProcess.isAlive()) {
            try {
                manualServerWriter.write(cmd + "\n");
                manualServerWriter.flush();
            } catch (IOException e) {
                appendToConsole("Error sending to server: " + e.getMessage());
            }
        }
    }

    private static String translateAlignmentForPortrait(String label, boolean originRight, boolean originBottom) {
        boolean xor = originRight ^ originBottom;
        if (xor) {
            if ("Top Left".equals(label)) return "Bottom Right";
            if ("Bottom Right".equals(label)) return "Top Left";
        } else {
            if ("Top Right".equals(label)) return "Bottom Left";
            if ("Bottom Left".equals(label)) return "Top Right";
        }
        return label;
    }

    private void updateVisualSettings() {
        appendToConsole("[DEBUG] Visual Settings Update: Align=" + settingsPanel.getCanvasAlignment());
        visPanel.setMachineSize(settingsPanel.getMachineWidth(), settingsPanel.getMachineHeight());
        visPanel.setMachineOrigin(settingsPanel.getMachineOrigin());

        visPanel.setDataInvertX(settingsPanel.isInvertX());
        visPanel.setDataInvertY(settingsPanel.isInvertY());
        visPanel.setFlipY(settingsPanel.isFlipY());

        visPanel.setSwapXY(settingsPanel.isSwapXY());
        visPanel.setCanvasAlignment(settingsPanel.getCanvasAlignment());
        visPanel.setOrientation(settingsPanel.getOrientation());
        visPanel.setViewRotation(settingsPanel.getViewRotation());
        visPanel.setPadding(settingsPanel.getPaddingX(), settingsPanel.getPaddingY());

        List<VisualizationPanel.Station> visualStations = new ArrayList<>();
        Map<String, StationConfig> stations = settingsPanel.getStations();
        if (stations != null) {
            for (Map.Entry<String, StationConfig> entry : stations.entrySet()) {
                StationConfig cfg = entry.getValue();
                visualStations.add(new VisualizationPanel.Station(entry.getKey(), cfg.x(), cfg.y()));
            }
        }
        visPanel.setStations(visualStations);
    }

    private void appendToConsole(String text) {
        consoleArea.append(text + "\n");
    }

    private void updateStatus(boolean connected) {
        Window win = SwingUtilities.getWindowAncestor(this);
        if (win instanceof MainFrame) {
            ((MainFrame) win).setConnectionStatus(connected);
        }
    }
}
